"""empty message

Revision ID: 8eab1129aa2b
Revises: db4ffa12375f
Create Date: 2021-08-04 00:15:30.730761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eab1129aa2b'
down_revision = 'db4ffa12375f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Show_Venue_id_fkey', 'Show', type_='foreignkey')
    op.drop_constraint('Show_Artist_id_fkey', 'Show', type_='foreignkey')
    op.create_foreign_key(None, 'Show', 'Venue', ['Venue_id'], ['id'])
    op.create_foreign_key(None, 'Show', 'Artist', ['Artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.create_foreign_key('Show_Artist_id_fkey', 'Show', 'Artist', ['Artist_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('Show_Venue_id_fkey', 'Show', 'Venue', ['Venue_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
