"""empty message

Revision ID: e9c7f41e1344
Revises: 3aa04ae2f5d4
Create Date: 2021-07-31 15:16:55.534875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9c7f41e1344'
down_revision = '3aa04ae2f5d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('show', 'Venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('show', 'Artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('show_Venue_id_fkey', 'show', type_='foreignkey')
    op.drop_constraint('show_Artist_id_fkey', 'show', type_='foreignkey')
    op.create_foreign_key(None, 'show', 'Venue', ['Venue_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'show', 'Artist', ['Artist_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.create_foreign_key('show_Artist_id_fkey', 'show', 'Artist', ['Artist_id'], ['id'])
    op.create_foreign_key('show_Venue_id_fkey', 'show', 'Venue', ['Venue_id'], ['id'])
    op.alter_column('show', 'Artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('show', 'Venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
